import {
  jest,
  beforeEach,
  afterEach,
  describe,
  expect,
  it,
} from '@jest/globals';
import type { OutputFileDetail } from '@autographcraft/core';

// ESM mock factories must provide every export the module graph reaches for -
// a missing one is a SyntaxError, not `undefined` - so spread the real module
// and override only the logger this suite asserts against.
const actualCore = jest.requireActual<typeof import('@autographcraft/core')>(
  '@autographcraft/core'
);

jest.unstable_mockModule('@autographcraft/core', () => ({
  ...actualCore,
  logger: {
    info: jest.fn(),
    warn: jest.fn(),
    error: jest.fn(),
  },
}));

// `../helpers` re-exports `validateSchema`, which pulls in @graphql-codegen/cli;
// codegen 7 depends on yargs 18 and chalk 5, neither of which Jest's ESM loader
// can link. Mocking the barrel avoids loading it, while the real
// `addIgnoreHeaderToContent` is still wrapped in the spy so the header written
// to disk is the genuine one and the file extension it is handed can be
// asserted directly.
const actualAddIgnoreHeaderToContent = jest.requireActual<
  typeof import('../../helpers/addIgnoreHeaderToContent')
>('../../helpers/addIgnoreHeaderToContent').addIgnoreHeaderToContent;

const addIgnoreHeaderToContent = jest.fn(actualAddIgnoreHeaderToContent);

jest.unstable_mockModule('../../helpers', () => ({
  addIgnoreHeaderToContent,
}));

// ESM has no automocking. The `node:fs` mock also stands in for `fs`, which
// modules deeper in the graph (yargs, reached via `src/helpers`) import from,
// so the real module is spread and only the three members this unit calls are
// replaced - otherwise those deeper imports fail to link.
const existsSync = jest.fn<(path: string) => boolean>();
const writeFileSync = jest.fn<(path: string, contents: string) => void>();
const mkdirSync =
  jest.fn<(path: string, options: { recursive: boolean }) => void>();

const actualFs = jest.requireActual<typeof import('node:fs')>('node:fs');
const fsMock = {
  ...actualFs,
  existsSync,
  writeFileSync,
  mkdirSync,
};

jest.unstable_mockModule('node:fs', () => ({ ...fsMock, default: fsMock }));

const { logger } = await import('@autographcraft/core');
const { writeFilesToFileSystem } = await import('../writeFilesToFileSystem');

const JAVASCRIPT_HEADER = [
  '/* eslint-disable */',
  '// @ts-nocheck',
  '// prettier-ignore',
  '// This file has been generated by AutoGraph. Do not edit this file directly.',
  '// Any changes made to this file will be overwritten when AutoGraphCraft is next run.',
  '',
  '',
].join('\n');

function getOutputFile(
  overrides: Partial<OutputFileDetail> = {}
): OutputFileDetail {
  return {
    filePath: '/project/generated/models/User.ts',
    content: 'export const a = 1;',
    addIgnoreHeader: false,
    shouldOverwrite: true,
    ...overrides,
  };
}

describe('writeFilesToFileSystem', () => {
  beforeEach(() => {
    jest.clearAllMocks();
    existsSync.mockReturnValue(true);
    jest.spyOn(process, 'cwd').mockReturnValue('/project');
  });

  afterEach(() => {
    jest.restoreAllMocks();
  });

  it('should be defined', () => {
    // Assert
    expect(writeFilesToFileSystem).toBeDefined();
  });

  it('should write nothing and report the dry run when isDryRun is true', () => {
    // Act
    writeFilesToFileSystem([getOutputFile()], true);

    // Assert
    expect(writeFileSync).not.toHaveBeenCalled();
    expect(existsSync).not.toHaveBeenCalled();
    expect(logger.info).toHaveBeenCalledWith(
      'ℹ️ Dry run requested, no files will be written'
    );
  });

  it('should write the raw content when no ignore header is requested', () => {
    // Act
    writeFilesToFileSystem([getOutputFile()], false);

    // Assert
    expect(writeFileSync).toHaveBeenCalledWith(
      '/project/generated/models/User.ts',
      'export const a = 1;'
    );
  });

  it('should prepend the ignore header for the file extension when requested', () => {
    // Act
    writeFilesToFileSystem([getOutputFile({ addIgnoreHeader: true })], false);

    // Assert
    expect(writeFileSync).toHaveBeenCalledWith(
      '/project/generated/models/User.ts',
      `${JAVASCRIPT_HEADER}export const a = 1;`
    );
  });

  it('should use the graphql ignore header for a graphql file', () => {
    // Act
    writeFilesToFileSystem(
      [
        getOutputFile({
          filePath: '/project/generated/typeDefs.graphql',
          content: 'type Test { id: ID }',
          addIgnoreHeader: true,
        }),
      ],
      false
    );

    // Assert
    expect(addIgnoreHeaderToContent).toHaveBeenCalledWith(
      'type Test { id: ID }',
      'graphql'
    );
    const [, contents] = writeFileSync.mock.calls[0];
    expect(contents.startsWith('# This file has been generated')).toBe(true);
  });

  it('should derive the extension from the file name', () => {
    // Act
    writeFilesToFileSystem([getOutputFile({ addIgnoreHeader: true })], false);

    // Assert
    expect(addIgnoreHeaderToContent).toHaveBeenCalledWith(
      'export const a = 1;',
      'ts'
    );
  });

  it('should use only the final part of a multi-part extension', () => {
    // Act
    writeFilesToFileSystem(
      [
        getOutputFile({
          filePath: '/project/generated/schema.d.ts',
          addIgnoreHeader: true,
        }),
      ],
      false
    );

    // Assert
    expect(addIgnoreHeaderToContent).toHaveBeenCalledWith(
      'export const a = 1;',
      'ts'
    );
  });

  it.each([
    ['a file name with no dot', '/project/generated/Makefile'],
    ['a dotfile', '/project/generated/.gitignore'],
    ['a dot in a directory name', '/project/src/v1.2/Makefile'],
    ['a dotfile below a dotted directory', '/project/src/v1.2/.gitignore'],
    ['a trailing dot', '/project/generated/Makefile.'],
    ['an empty file path', ''],
  ])('should derive no extension from %s', (_description, filePath) => {
    // Act
    writeFilesToFileSystem(
      [getOutputFile({ filePath, addIgnoreHeader: true })],
      false
    );

    // Assert
    expect(addIgnoreHeaderToContent).toHaveBeenCalledWith(
      'export const a = 1;',
      ''
    );
  });

  it('should still write the javascript header for a path with no extension', () => {
    // Act
    writeFilesToFileSystem(
      [
        getOutputFile({
          filePath: '/project/generated/Makefile',
          addIgnoreHeader: true,
        }),
      ],
      false
    );

    // Assert
    const [, contents] = writeFileSync.mock.calls[0];
    expect(contents).toBe(`${JAVASCRIPT_HEADER}export const a = 1;`);
  });

  it('should not add a header when none is requested, whatever the extension', () => {
    // Act
    writeFilesToFileSystem(
      [getOutputFile({ filePath: '/project/generated/Makefile' })],
      false
    );

    // Assert
    expect(addIgnoreHeaderToContent).not.toHaveBeenCalled();
    expect(writeFileSync).toHaveBeenCalledWith(
      '/project/generated/Makefile',
      'export const a = 1;'
    );
  });

  it('should skip a file that already exists and must not be overwritten', () => {
    // Arrange
    existsSync.mockReturnValue(true);

    // Act
    writeFilesToFileSystem([getOutputFile({ shouldOverwrite: false })], false);

    // Assert
    expect(writeFileSync).not.toHaveBeenCalled();
    expect(logger.info).not.toHaveBeenCalled();
  });

  it('should write a file that must not be overwritten when it does not yet exist', () => {
    // Arrange
    existsSync.mockReturnValue(false);

    // Act
    writeFilesToFileSystem([getOutputFile({ shouldOverwrite: false })], false);

    // Assert
    expect(writeFileSync).toHaveBeenCalledTimes(1);
  });

  it('should create the containing directory when it does not exist', () => {
    // Arrange: the file does not exist, and neither does its directory
    existsSync.mockReturnValue(false);

    // Act
    writeFilesToFileSystem([getOutputFile()], false);

    // Assert
    expect(mkdirSync).toHaveBeenCalledWith('/project/generated/models', {
      recursive: true,
    });
  });

  it('should not create the containing directory when it already exists', () => {
    // Arrange: the file does not exist, but its directory does
    existsSync.mockReturnValueOnce(false).mockReturnValueOnce(true);

    // Act
    writeFilesToFileSystem([getOutputFile()], false);

    // Assert
    expect(mkdirSync).not.toHaveBeenCalled();
    expect(writeFileSync).toHaveBeenCalledTimes(1);
  });

  it('should log each written file path relative to the current working directory', () => {
    // Act
    writeFilesToFileSystem([getOutputFile()], false);

    // Assert
    expect(logger.info).toHaveBeenCalledWith(
      '✅ File written: generated/models/User.ts'
    );
  });

  it('should write every output file it is given', () => {
    // Arrange
    const outputFiles = [
      getOutputFile({ filePath: '/project/generated/a.ts' }),
      getOutputFile({ filePath: '/project/generated/b.ts' }),
      getOutputFile({ filePath: '/project/generated/c.ts' }),
    ];

    // Act
    writeFilesToFileSystem(outputFiles, false);

    // Assert
    expect(writeFileSync).toHaveBeenCalledTimes(3);
  });

  it('should do nothing when there are no output files', () => {
    // Act
    writeFilesToFileSystem([], false);

    // Assert
    expect(writeFileSync).not.toHaveBeenCalled();
    expect(logger.info).not.toHaveBeenCalled();
  });
});
