import { describe, expect, it } from '@jest/globals';
import { addIgnoreHeaderToContent } from '../addIgnoreHeaderToContent';

const CONTENT = 'const a = 1;\n';

const JAVASCRIPT_HEADER = [
  '/* eslint-disable */',
  '// @ts-nocheck',
  '// prettier-ignore',
  '// This file has been generated by AutoGraph. Do not edit this file directly.',
  '// Any changes made to this file will be overwritten when AutoGraphCraft is next run.',
  '',
].join('\n');

const GRAPHQL_HEADER = [
  '# This file has been generated by AutoGraph. Do not edit this file directly.',
  '# Any changes made to this file will be overwritten when AutoGraphCraft is next run.',
  '',
].join('\n');

describe('addIgnoreHeaderToContent', () => {
  it('should be defined', () => {
    // Assert
    expect(addIgnoreHeaderToContent).toBeDefined();
  });

  it('should prepend the javascript comment header for a js file', () => {
    // Act
    const result = addIgnoreHeaderToContent(CONTENT, 'js');

    // Assert
    expect(result).toBe(`${JAVASCRIPT_HEADER}\n${CONTENT}`);
  });

  it('should prepend the typescript comment header for a ts file', () => {
    // Act
    const result = addIgnoreHeaderToContent(CONTENT, 'ts');

    // Assert
    expect(result).toBe(`${JAVASCRIPT_HEADER}\n${CONTENT}`);
    expect(result).toContain('// @ts-nocheck');
  });

  it('should prepend the hash comment header for a graphql file', () => {
    // Act
    const result = addIgnoreHeaderToContent(CONTENT, 'graphql');

    // Assert
    expect(result).toBe(`${GRAPHQL_HEADER}\n${CONTENT}`);
    expect(result).not.toContain('/* eslint-disable */');
  });

  it('should fall back to the javascript comment header for an unknown extension', () => {
    // Act
    const result = addIgnoreHeaderToContent(CONTENT, 'md');

    // Assert
    expect(result).toBe(`${JAVASCRIPT_HEADER}\n${CONTENT}`);
  });

  it('should fall back to the javascript comment header for an empty extension', () => {
    // Act
    const result = addIgnoreHeaderToContent('', '');

    // Assert
    expect(result).toBe(`${JAVASCRIPT_HEADER}\n`);
  });
});
